<a href="https://colab.research.google.com/github/noorwewe/Intelligent-System/blob/Recurrent-neural-network/BAM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Import Library

In [0]:
import numpy as np

Menghitung matrix W dan pengujian

In [7]:
X1 = np.matrix([1,1,1,1,1,1])
Y1 = np.matrix([1,1,1])
X2 = np.matrix([-1,-1,-1,-1,-1,-1])
Y2 = np.matrix([-1,-1,-1])
X3 = np.matrix([1,1,-1,-1,1,1])
Y3 = np.matrix([1,-1,1])
X4 = np.matrix([-1,-1,1,1,-1,-1])
Y4 = np.matrix([-1,1,-1])

W = np.multiply(np.transpose(X1),Y1) + np.multiply(np.transpose(X2),Y2) + np.multiply(np.transpose(X3),Y3) + np.multiply(np.transpose(X4),Y4) 

Yinput1 = np.transpose(X1)
Yinput2 = np.transpose(X2)
Yinput3 = np.transpose(X3)
Yinput4 = np.transpose(X4)
Yout1 = np.sign(np.matmul(np.transpose(W),Yinput1))
Yout2 = np.sign(np.matmul(np.transpose(W),Yinput2))
Yout3 = np.sign(np.matmul(np.transpose(W),Yinput3))
Yout4 = np.sign(np.matmul(np.transpose(W),Yinput4))

comparison1 = Yout1 == np.transpose(Y1)
comparison2 = Yout2 == np.transpose(Y2)
comparison3 = Yout3 == np.transpose(Y3)
comparison4 = Yout4 == np.transpose(Y4)

if comparison1.all():
  print("State 1 Valid")
if comparison2.all():
  print("State 2 Valid")
if comparison3.all():
  print("State 3 Valid")
if comparison4.all():
  print("State 4 Valid")

State 1 Valid
State 2 Valid
State 3 Valid
State 4 Valid


Iterasi Asosiasi X ke Y dan sebaliknya

In [24]:
inputan = np.transpose(np.matrix([-1,1,1,1,1,1]))
for j in range(10):
  if len(inputan) == 6:
    inputan=np.sign(np.matmul(np.transpose(W),inputan))
  else:
    inputan=np.sign(np.matmul(W,inputan))
  p = j+1
  print ("------")
  print("Iterasi ke")
  print(p)
  print("Hasil Iterasi (X atau Y)")
  print(inputan)
  print ("------")

------
Iterasi ke
1
Hasil Iterasi (X atau Y)
[[1]
 [1]
 [1]]
------
------
Iterasi ke
2
Hasil Iterasi (X atau Y)
[[1]
 [1]
 [1]
 [1]
 [1]
 [1]]
------
------
Iterasi ke
3
Hasil Iterasi (X atau Y)
[[1]
 [1]
 [1]]
------
------
Iterasi ke
4
Hasil Iterasi (X atau Y)
[[1]
 [1]
 [1]
 [1]
 [1]
 [1]]
------
------
Iterasi ke
5
Hasil Iterasi (X atau Y)
[[1]
 [1]
 [1]]
------
------
Iterasi ke
6
Hasil Iterasi (X atau Y)
[[1]
 [1]
 [1]
 [1]
 [1]
 [1]]
------
------
Iterasi ke
7
Hasil Iterasi (X atau Y)
[[1]
 [1]
 [1]]
------
------
Iterasi ke
8
Hasil Iterasi (X atau Y)
[[1]
 [1]
 [1]
 [1]
 [1]
 [1]]
------
------
Iterasi ke
9
Hasil Iterasi (X atau Y)
[[1]
 [1]
 [1]]
------
------
Iterasi ke
10
Hasil Iterasi (X atau Y)
[[1]
 [1]
 [1]
 [1]
 [1]
 [1]]
------
