<a href="https://colab.research.google.com/github/noorwewe/Intelligent-System/blob/Recurrent-neural-network/BAM_NeuPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
pip install neupy

     |████████████████████████████████| 235kB 2.8MB/s 
     |████████████████████████████████| 92.6MB 71kB/s 
     |████████████████████████████████| 3.2MB 35.6MB/s 
     |████████████████████████████████| 368kB 49.8MB/s 
  Found existing installation: progressbar2 3.38.0
    Uninstalling progressbar2-3.38.0:
      Successfully uninstalled progressbar2-3.38.0
  Found existing installation: tensorboard 2.2.0
    Uninstalling tensorboard-2.2.0:
      Successfully uninstalled tensorboard-2.2.0
  Found existing installation: tensorflow-estimator 2.2.0rc0
    Uninstalling tensorflow-estimator-2.2.0rc0:
      Successfully uninstalled tensorflow-estimator-2.2.0rc0
  Found existing installation: tensorflow 2.2.0rc3
    Uninstalling tensorflow-2.2.0rc3:
      Successfully uninstalled tensorflow-2.2.0rc3
  Found existing installation: graphviz 0.10.1
    Uninstalling graphviz-0.10.1:
      Successfully uninstalled graphviz-0.10.1


In [0]:
import numpy as np
from neupy import algorithms

In [0]:
zero = np.matrix([
...     0, 1, 1, 1, 0,
...     1, 0, 0, 0, 1,
...     1, 0, 0, 0, 1,
...     1, 0, 0, 0, 1,
...     1, 0, 0, 0, 1,
...     0, 1, 1, 1, 0
... ])

In [0]:
one = np.matrix([
...     0, 1, 1, 0, 0,
...     0, 0, 1, 0, 0,
...     0, 0, 1, 0, 0,
...     0, 0, 1, 0, 0,
...     0, 0, 1, 0, 0,
...     0, 0, 1, 0, 0
... ])

In [0]:
zero.reshape((5, 6))

In [0]:
half_zero = np.matrix([
...     0, 1, 1, 1, 0,
...     1, 0, 0, 0, 1,
...     1, 0, 0, 0, 1,
...     0, 0, 0, 0, 0,
...     0, 0, 0, 0, 0,
...     0, 0, 0, 0, 0,
... ])

In [0]:
half_one = np.matrix([
...     0, 1, 1, 0, 0,
...     0, 0, 1, 0, 0,
...     0, 0, 1, 0, 0,
...     0, 0, 0, 0, 0,
...     0, 0, 0, 0, 0,
...     0, 0, 0, 0, 0
... ])

In [0]:
zero_hint = np.matrix([[0, 1, 0, 0]])

In [0]:
one_hint = np.matrix([[1, 0, 0, 0]])

In [20]:
data = np.concatenate([zero, one], axis=0)
print(data)

[[0 1 1 1 0 1 0 0 0 1 1 0 0 0 1 1 0 0 0 1 1 0 0 0 1 0 1 1 1 0]
 [0 1 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0]]


In [21]:
hints = np.concatenate([zero_hint, one_hint], axis=0)
print(hints)

[[0 1 0 0]
 [1 0 0 0]]


In [0]:
bamnet = algorithms.DiscreteBAM(mode='sync')

In [0]:
bamnet.train(data, hints)

In [0]:
recovered_zero, recovered_hint = bamnet.predict(half_zero)

In [18]:
recovered_hint

array([[0, 1, 0, 0]])

In [19]:
zero_hint

matrix([[0, 1, 0, 0]])

In [0]:
recovered_one, recovered_hint = bamnet.predict(half_one)

In [25]:
recovered_hint

array([[1, 0, 0, 0]])

In [26]:
one_hint

matrix([[1, 0, 0, 0]])