<a href="https://colab.research.google.com/github/noorwewe/Intelligent-System/blob/Recurrent-neural-network/Hopfield_Neurolab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
!pip install neurolab

     |████████████████████████████████| 655kB 2.8MB/s 
  Created wheel for neurolab: filename=neurolab-0.3.5-cp36-none-any.whl size=22180 sha256=1f59d64d54acba8cd29eb03e6975a62d4ebd857b8af286839bac64ea6a87b2e1
  Stored in directory: /root/.cache/pip/wheels/c6/8f/37/32ab1cf4d601dc0bc49d7241012a4292db4b343bebff5b68e6
Successfully built neurolab


In [0]:
# -*- coding: utf-8 -*-
"""
Example of use Hopfield Recurrent network
=========================================

Task: Recognition of positive and negative arrays

"""

import numpy as np
import neurolab as nl

# 
target =  [[1,1,1,1],
          [-1,-1,-1,-1]]

chars = ['Positif', 'Negatif']
target = np.asfarray(target)

# Create and train network
net = nl.net.newhop(target)

print("\nTest on Target:")
output = net.sim(target)
print(output)

print("\nTest on distorted Positif:")
test =np.asfarray([1,-1,1,1])
print(test)
out = net.sim([test])
print(out)

print("\nTest on distorted Negatif:")
test =np.asfarray([1,-1,-1,-1])
print(test)
out = net.sim([test])
print(out)



Test on Target:
[[ 1.  1.  1.  1.]
 [-1. -1. -1. -1.]]

Test on distorted Positif:
[ 1. -1.  1.  1.]
[[1. 1. 1. 1.]]

Test on distorted Negatif:
[ 1. -1. -1. -1.]
[[-1. -1. -1. -1.]]
