<a href="https://colab.research.google.com/github/noorwewe/Intelligent-System/blob/Recurrent-neural-network/Hopfield.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Import library 

In [0]:
import numpy as np

Menghitung matriks W dan pengujian

In [86]:
Y1 = np.matrix([1,1,1])
Y2 = np.matrix([-1,-1,-1])
Theta = np.transpose(np.matrix([0,0,0]))
W = np.multiply(Y1,np.transpose(Y1)) + np.multiply(Y2, np.transpose(Y2))- 2*np.eye(3)
Yinput1 = np.transpose(Y1)
Yinput2 = np.transpose(Y2)
Yout1 = np.sign(np.matmul(W,Yinput1))
Yout2 = np.sign(np.matmul(W,Yinput2))
comparison1 = Yout1 == Yinput1
comparison2 = Yout2 == Yinput2
if comparison1.all():
  print("State 1 Valid")
if comparison2.all():
  print("State 2 Valid")

State 1 Valid
State 2 Valid


Iterasi error correction

In [87]:
Yinput = np.transpose(np.matrix([-1,1,1]))
for j in range(10):
  Yout=np.sign(np.matmul(W,Yinput)-Theta)
  Yinput = Yout
  p = j+1
  print ("------")
  print("Iterasi ke")
  print(p)
  print("Hasil Yout")
  print(Yout)
  print ("------")

------
Iterasi ke
1
Hasil Yout
[[1.]
 [0.]
 [0.]]
------
------
Iterasi ke
2
Hasil Yout
[[0.]
 [1.]
 [1.]]
------
------
Iterasi ke
3
Hasil Yout
[[1.]
 [1.]
 [1.]]
------
------
Iterasi ke
4
Hasil Yout
[[1.]
 [1.]
 [1.]]
------
------
Iterasi ke
5
Hasil Yout
[[1.]
 [1.]
 [1.]]
------
------
Iterasi ke
6
Hasil Yout
[[1.]
 [1.]
 [1.]]
------
------
Iterasi ke
7
Hasil Yout
[[1.]
 [1.]
 [1.]]
------
------
Iterasi ke
8
Hasil Yout
[[1.]
 [1.]
 [1.]]
------
------
Iterasi ke
9
Hasil Yout
[[1.]
 [1.]
 [1.]]
------
------
Iterasi ke
10
Hasil Yout
[[1.]
 [1.]
 [1.]]
------
